# Generated by Django 4.2.8 on 2025-06-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='產品名稱')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='產品單價')),
            ],
            options={
                'verbose_name': '產品',
                'verbose_name_plural': '產品',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='api.product', verbose_name='包含產品'),
        ),
    ]
